package codegen

import (
	"io"
	"strings"
	"text/template"

	"github.com/intervinn/btxpack/layout"
)

func ToPascalCase(s string) string {
	words := strings.FieldsFunc(s, func(r rune) bool {
		return r == ' ' || r == '_' || r == '-' || r == '/' || r == '\\' || r == '.'
	})

	var sb strings.Builder
	sb.Grow(len(s) + 4)

	sb.WriteString("Btx_")
	for _, word := range words {
		if len(word) == 0 {
			continue
		}

		runes := []rune(word)

		sb.WriteString(strings.ToUpper(string(runes[0])))
		sb.WriteString(strings.ToLower(string(runes[1:])))
	}

	return sb.String()
}

var templateC = `// generated by btxpack (https://github.com/intervinn/btxpack)
#ifndef __BTXPACK_ATLAS_META_H
#define __BTXPACK_ATLAS_META_H

#ifdef BTXPACK_IMPLEMENTATION
	#define BTX_API const
#else
	#define BTX_API extern const
#endif

struct _btxpack_rec {
	float x;
	float y;
	float width;
	float height;
};

{{range .}}BTX_API _btxpack_rec {{ToPascal .Name}} = { {{.X}}, {{.Y}}, {{.W}}, {{.H}} }; 
{{end}}
#endif // __BTXPACK_ATLAS_META_H
`

var templateRaylibC = `// generated by btxpack (https://github.com/intervinn/btxpack)
#ifndef __BTXPACK_ATLAS_META_H
#define __BTXPACK_ATLAS_META_H

#include "raylib.h"

#ifdef BTXPACK_IMPLEMENTATION
	#define BTX_API const
#else
	#define BTX_API extern const
#endif

{{range .}}BTX_API Rectangle {{ToPascal .Name}} = { {{.X}}, {{.Y}}, {{.W}}, {{.H}} }; 
{{end}}
#endif // __BTXPACK_ATLAS_META_H
`

func WriteAtlasC(metas []layout.Meta, to io.Writer) error {
	funcs := template.FuncMap{
		"ToPascal": ToPascalCase,
	}

	tmpl, err := template.New("codegen").Funcs(funcs).Parse(templateC)
	if err != nil {
		return err
	}

	return tmpl.Execute(to, metas)
}

func WriteAtlasRaylibC(metas []layout.Meta, to io.Writer) error {
	funcs := template.FuncMap{
		"ToPascal": ToPascalCase,
	}

	tmpl, err := template.New("codegen").Funcs(funcs).Parse(templateRaylibC)
	if err != nil {
		return err
	}

	return tmpl.Execute(to, metas)
}
